/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;
import java.time.LocalDate;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import logica.DTO.DTOPropuesta;
import logica.Fabrica;
import logica.IController;
import logica.DTO.TipoRetorno;
import logica.DTO.Estado;
public class AltaPropuesta extends javax.swing.JInternalFrame {
    private IController controller = Fabrica.getInstance().getController();
    private String rutaImagen = null; 
    String categoria;
    /**
     * Creates new form AltaPropuesta
     */
    public AltaPropuesta() {
        initComponents();
        TituloField.setName("Título");
        Descripcion_Field.setName("Descripción");
        Lugar_Field.setName("Lugar");
        Precio_Field.setName("Precio");
        Monto_Field.setName("Monto");
        d.setName("Día");
        m.setName("Mes");
        a.setName("Año");
        ListaUsuarios.removeAllItems();
        ListaUsuarios.setSelectedIndex(-1);
        for (String u : controller.ListaProponentes()) {
            ListaUsuarios.addItem(u); 
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloAgregarPropuesta = new javax.swing.JLabel();
        ListaUsuarios = new javax.swing.JComboBox<>();
        IngresoUsuario = new javax.swing.JLabel();
        IngresoCategoria = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        TituloField = new javax.swing.JTextField();
        Descripcion = new javax.swing.JLabel();
        Lugar = new javax.swing.JLabel();
        Precio_Entrada = new javax.swing.JLabel();
        Monto_A_Recaudar = new javax.swing.JLabel();
        Descripcion_Field = new javax.swing.JTextField();
        Lugar_Field = new javax.swing.JTextField();
        Precio_Field = new javax.swing.JTextField();
        Monto_Field = new javax.swing.JTextField();
        Agregar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Imagen_Boton = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        m = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        T2 = new javax.swing.JCheckBox();
        T1 = new javax.swing.JCheckBox();
        ListaCategoria = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agregar Propuesta");

        TituloAgregarPropuesta.setText("Ingrese los siguientes datos");

        ListaUsuarios.setToolTipText("");
        ListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaUsuariosActionPerformed(evt);
            }
        });

        IngresoUsuario.setText("Proponente");

        IngresoCategoria.setText("Categoria");

        Titulo.setText("Titulo");

        TituloField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloFieldActionPerformed(evt);
            }
        });

        Descripcion.setText("Descripcion");

        Lugar.setText("Lugar");

        Precio_Entrada.setText("Precio Entrada");

        Monto_A_Recaudar.setText("Monto a recaudar");

        Descripcion_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Descripcion_FieldActionPerformed(evt);
            }
        });

        Lugar_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lugar_FieldActionPerformed(evt);
            }
        });

        Precio_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio_FieldActionPerformed(evt);
            }
        });

        Monto_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Monto_FieldActionPerformed(evt);
            }
        });

        Agregar.setText("Crear");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Imagen_Boton.setText("Subir");
        Imagen_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen_BotonActionPerformed(evt);
            }
        });

        Imagen.setText("Imagen");

        jLabel7.setText("Fecha ");

        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        jLabel8.setText("Año");

        jLabel9.setText("Mes");

        jLabel10.setText("Dia");

        jLabel6.setText("Retorno");

        T2.setText("Entrada Gratis");
        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });

        T1.setText("Porcentaje de Ganancia");
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });

        ListaCategoria.setText("Seleccion de Categoria");
        ListaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(TituloAgregarPropuesta))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Descripcion)
                                .addComponent(Titulo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Descripcion_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TituloField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(IngresoUsuario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ListaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(IngresoCategoria)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ListaCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(64, 64, 64)
                                    .addComponent(Imagen)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Agregar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Cancelar))
                                        .addComponent(Imagen_Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lugar)
                                    .addComponent(Precio_Entrada)
                                    .addComponent(jLabel6)
                                    .addComponent(Monto_A_Recaudar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lugar_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Monto_Field)
                                        .addComponent(Precio_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(T2)
                                    .addComponent(T1))))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloAgregarPropuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IngresoUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresoCategoria)
                    .addComponent(ListaCategoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo)
                    .addComponent(TituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Descripcion_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lugar_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lugar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Precio_Entrada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Monto_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Monto_A_Recaudar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(T2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Imagen_Boton)
                    .addComponent(Imagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Agregar))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void AsignarCategoria(String cat){
        this.categoria=cat;
        ListaCategoria.setText(categoria);
    }
           
    private void TituloFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloFieldActionPerformed
        
    }//GEN-LAST:event_TituloFieldActionPerformed

    private void Descripcion_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Descripcion_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Descripcion_FieldActionPerformed

    private void Lugar_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lugar_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lugar_FieldActionPerformed

    private void Precio_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio_FieldActionPerformed

    private void Monto_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Monto_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Monto_FieldActionPerformed
    private boolean validarCampo(List<JTextField> campos) {
        for (JTextField campo : campos) {
            if (campo.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "El campo '" + campo.getName() + "' no puede estar vacío",
                        "Error", JOptionPane.ERROR_MESSAGE);
                campo.requestFocus();
                return false;
            }
        }
        try {
            Integer.parseInt(Precio_Field.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El campo Precio debe ser un numero entero", "Error", JOptionPane.ERROR_MESSAGE);
            Precio_Field.requestFocus();
            return false;
        }
        try {
            Integer.parseInt(Monto_Field.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El campo Monto debe ser un numero entero", "Error", JOptionPane.ERROR_MESSAGE);
            Monto_Field.requestFocus();
            return false;
        }
        if (!Utilities.validarFecha(d.getText(), m.getText(), a.getText())) {
            return false;
        }
       
        return true; 
    }
    public static boolean validarRetorno(JCheckBox t1, JCheckBox t2) {
        if (!t1.isSelected() && !t2.isSelected()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar al menos un tipo de retorno",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed

        List<JTextField> campos = Arrays.asList(TituloField, Descripcion_Field, Lugar_Field, Precio_Field, Monto_Field, d, m, a);
        if (!validarCampo(campos)) {
            return;
        }
        String titulo = TituloField.getText();
        String descripcion = Descripcion_Field.getText();
        String lugar = Lugar_Field.getText();
        int precio = Integer.parseInt(Precio_Field.getText().trim());
        int montoTotal = Integer.parseInt(Monto_Field.getText().trim());
        String dia = d.getText(); 
        String mes =m.getText(); 
        String anio =a.getText();
        //LocalDate hoy = LocalDate.now();
        //DTFecha fechaCreacion = new DTFecha(hoy.getDayOfMonth(), hoy.getMonthValue(), hoy.getYear());
        ListaUsuarios.getSelectedItem();

        List<TipoRetorno> retorno = new ArrayList<>();
        if (T2.isSelected()) {
            retorno.add(TipoRetorno.EntradaGratis);
        }
        if (T1.isSelected()) {
            retorno.add(TipoRetorno.PorcentajeGanancia);
        }
        String usuarios = (String) ListaUsuarios.getSelectedItem(); 
        
        if(validarCampo(campos) && validarRetorno(T1,T2)){
            if(controller.existeProp(titulo)){    
                JOptionPane.showMessageDialog(this, "Propuesta ya registrada");
            }else{
                Utilities.copiarImagen(rutaImagen,titulo);
                LocalDate  fechaEvento=LocalDate.of(Integer.parseInt(anio),Integer.parseInt(mes),Integer.parseInt(dia));
                controller.altaPropuesta(titulo, descripcion, rutaImagen, lugar, fechaEvento, precio, montoTotal,LocalDate.now() ,retorno,categoria, usuarios,Estado.INGRESADA);
                JOptionPane.showMessageDialog(this, "Propuesta registrado con exito");
                TituloField.setText("");
                Descripcion_Field.setText("");
                Lugar_Field.setText("");
                Precio_Field.setText("");
                Monto_Field.setText("");
                ListaCategoria.setText("Seleccione Categoria");
                d.setText("");
                m.setText("");
                a.setText("");
                T2.setSelected(false);
                T1.setSelected(false);
                
                ListaUsuarios.setSelectedIndex(-1);
            }
            
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void Imagen_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen_BotonActionPerformed
        JFileChooser fileProp = new JFileChooser();
        fileProp .setDialogTitle("Seleccionar imagen");
        fileProp .setFileSelectionMode(JFileChooser.FILES_ONLY);
     
        fileProp.setAcceptAllFileFilterUsed(false);
        fileProp .addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Imagenes", "jpg","png"));

        int resultado = fileProp.showOpenDialog(this); 

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileProp.getSelectedFile();
            rutaImagen= archivo.getAbsolutePath(); 
           // System.out.println("Imagen seleccionada: " + rutaImagen);
        }
    }//GEN-LAST:event_Imagen_BotonActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed

    }//GEN-LAST:event_dActionPerformed

    private void ListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaUsuariosActionPerformed

        /*
        DTOProponente seleccionado = (DTOProponente) ListaUsuarios.getSelectedItem();

        if (seleccionado != null )
        {
            //si selecciona algo mal (en proceso)
        }

        */
    }//GEN-LAST:event_ListaUsuariosActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2ActionPerformed

    private void ListaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCategoriaActionPerformed
        
        SelectCategoria mostrar = new SelectCategoria(this);
        JDesktopPane fondo3Final = this.getDesktopPane();
        fondo3Final.add(mostrar);
        mostrar.setSize(fondo3Final.getSize());
        mostrar.setVisible(true);
        
    }//GEN-LAST:event_ListaCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JTextField Descripcion_Field;
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton Imagen_Boton;
    private javax.swing.JLabel IngresoCategoria;
    private javax.swing.JLabel IngresoUsuario;
    private javax.swing.JButton ListaCategoria;
    private javax.swing.JComboBox<String> ListaUsuarios;
    private javax.swing.JLabel Lugar;
    private javax.swing.JTextField Lugar_Field;
    private javax.swing.JLabel Monto_A_Recaudar;
    private javax.swing.JTextField Monto_Field;
    private javax.swing.JLabel Precio_Entrada;
    private javax.swing.JTextField Precio_Field;
    private javax.swing.JCheckBox T1;
    private javax.swing.JCheckBox T2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloAgregarPropuesta;
    private javax.swing.JTextField TituloField;
    private javax.swing.JTextField a;
    private javax.swing.JTextField d;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField m;
    // End of variables declaration//GEN-END:variables
}
