/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;
import java.time.LocalDate;
import java.util.List;
import logica.DTO.DTOPropuesta;
import logica.Fabrica;
import logica.IController;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import logica.DTO.Estado;
import logica.DTO.TipoRetorno;
/**
 *
 * @author asus
 */
public class EvaluarPropuesta extends javax.swing.JInternalFrame {
    private IController controller = Fabrica.getInstance().getController();
    private DTOPropuesta auxProp = null;
    /**
     * Creates new form EvaluarPropuesta
     */
    public EvaluarPropuesta() {
        initComponents();
        jComboBox1.addItem(Estado.PUBLICADA);
        jComboBox1.addItem(Estado.CANCELADA);
        Set<DTOPropuesta> propuestas = controller.obtenerPropuestas("INGRESADA");
        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        for (DTOPropuesta p : propuestas) {
            String texto = p.getTitulo() + " - " + p.getUsr().getNickname();
            modeloLista.addElement(texto);
        }
        PropEvaluacion.setModel(modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PropEvaluacion = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        PropEvaluacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PropEvaluacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PropEvaluacion);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione una Propuesta ");

        jLabel2.setText("Seleccione el nuevo Estado");

        jButton1.setText("Cancelar");

        jButton2.setText("Aplicar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addGap(20, 20, 20))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PropEvaluacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropEvaluacionMouseClicked
        if (evt.getClickCount() == 2)
        {
            String tituloSeleccionado = PropEvaluacion.getSelectedValue();//var donde guardo el titulo que apreto
            String[] partes = tituloSeleccionado.split(" - "); // separa en un array de Strings
            String tituloprop = partes[0];  
            Set<DTOPropuesta> propuestas = controller.obtenerPropuestas("INGRESADA");//obtengo todos las propuestas
            DTOPropuesta propuestaSeleccionada = null; //aux de propuesta para guardar la que tenga el mismo nombre al seleccionado

            for (DTOPropuesta p : propuestas) {
                if (p.getTitulo().equals(tituloprop)) { //guardo solo la que tenga el mismo titulo
                    propuestaSeleccionada = p;
                    break;
                }
            }
            if (propuestaSeleccionada != null) {  //si no esta vacio
                jLabel2.setText("Propuesta seleccionada: " + propuestaSeleccionada.getTitulo());
                auxProp=propuestaSeleccionada;
                }
            }
    }//GEN-LAST:event_PropEvaluacionMouseClicked
    private void aplicarCambio(DTOPropuesta propuestaSeleccionada) {
        if (propuestaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una propuesta primero.");
            return;
        }

        String auxTitulo = propuestaSeleccionada.getTitulo();
        String auxUsuario = propuestaSeleccionada.getProponente().getNickname();
        String auxD = propuestaSeleccionada.getDescripcion();
        String auxL = propuestaSeleccionada.getLugar();
        String auxR = propuestaSeleccionada.getImagen();
        LocalDate auxF = propuestaSeleccionada.getFecha();
        int auxP = propuestaSeleccionada.getPrecio();
        int auxM = propuestaSeleccionada.getMontoTotal();
        List<TipoRetorno> auxRet = propuestaSeleccionada.getRetorno();
        String auxC = propuestaSeleccionada.getCategoria().getNombreCategoria();

        Estado newEstado = (Estado) jComboBox1.getSelectedItem();
        controller.modificarPropuesta(auxTitulo, auxD, auxR, auxL, auxF, auxP, auxM, auxRet, auxC, auxUsuario, newEstado);
        JOptionPane.showMessageDialog(this, "Estado Modificado con exito");
        this.dispose();
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        aplicarCambio(this.auxProp);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> PropEvaluacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<Estado> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
