/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import java.util.Set;
import javax.swing.DefaultListModel;
import logica.DTO.DTOPropuesta;
import logica.Fabrica;
import logica.IController;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JDesktopPane;
/**
 *
 * @author asus
 */
public class ModificarDatosPropuesta extends javax.swing.JInternalFrame {
   
    private IController controller = Fabrica.getInstance().getController();
    
    public ModificarDatosPropuesta() {
        initComponents();
        Set<DTOPropuesta> propuestas = controller.obtenerPropuestas("");
        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        for (DTOPropuesta p : propuestas) {
            modeloLista.addElement(p.getTitulo());
        }
        ListaPropuesta.setModel(modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPropuesta = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Modificar Datos Propuesta");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione la Propuesta a Modificar");

        ListaPropuesta.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaPropuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaPropuestaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaPropuesta);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaPropuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaPropuestaMouseClicked
               if (evt.getClickCount() == 2) 
            {
                String tituloSeleccionado = ListaPropuesta.getSelectedValue();//var donde guardo el titulo que apreto
                Set<DTOPropuesta> propuestas = controller.obtenerPropuestas("");//obtengo todos las propuestas
                DTOPropuesta propuestaSeleccionada = null; //aux de propuesta para guardar la que tenga el mismo nombre al seleccionado

                for (DTOPropuesta p : propuestas) {
                    if (p.getTitulo().equals(tituloSeleccionado)) { //guardo solo la que tenga el mismo titulo
                        propuestaSeleccionada = p;
                        break;
                    }
                }
                if (propuestaSeleccionada != null) {  //si no esta vacio
                    ChangeDataProp datos = new ChangeDataProp();          
                    datos.obtenerT(propuestaSeleccionada);                               
                    JDesktopPane fond = getDesktopPane();
                    if (fond != null) {
                        fond.add(datos);
                        datos.setSize(fond.getSize());
                        datos.setVisible(true);
                       
                    }
                }
            }
    }//GEN-LAST:event_ListaPropuestaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaPropuesta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
